---
- name: Enable ksm systemd service
  ansible.builtin.service:
    name: ksm
    enabled: true
    state: started

- name: Enable ksmtuned systemd service
  ansible.builtin.service:
    name: ksmtuned
    enabled: true
    state: started
  when:
    - ansible_facts['pkg_mgr'] in ['dnf', 'apt']
